#include <stdio.h>
#include <unistd.h>
#include <sys/resource.h>

#include <bpf/libbpf.h>

int main(void)
{
    /* Allow BPF to use locked memory */
    struct rlimit rlim = {
        .rlim_cur = RLIM_INFINITY,
        .rlim_max = RLIM_INFINITY,
    };

    if (setrlimit(RLIMIT_MEMLOCK, &rlim) != 0)
    {
        perror("setrlimit(RLIMIT_MEMLOCK)");
        return 1;
    }

    /* Path generated by CMake */
    const char *bpf_file = BPF_OBJECT_PATH;

    /*
     * STEP 1:
     * Open the compiled eBPF object.
     */
    struct bpf_object *obj;

    obj = bpf_object__open_file(bpf_file, NULL);

    if (!obj)
    {
        fprintf(stderr,
                "Failed to open BPF object: %s\n",
                bpf_file);

        return 1;
    }

    printf("BPF object opened successfully.\n");

    /*
     * STEP 2:
     * Load the eBPF program into the kernel.
     *
     * Kernel verifier runs here.
     */
    int err = bpf_object__load(obj);

    if (err != 0)
    {
        fprintf(stderr,
                "Failed to load BPF object into kernel: %d\n",
                err);

        bpf_object__close(obj);
        return 1;
    }

    printf("BPF object loaded into kernel.\n");

    /*
     * STEP 3:
     * Find the eBPF program inside the object.
     */
    struct bpf_program *prog;

    prog = bpf_object__next_program(obj, NULL);

    if (!prog)
    {
        fprintf(stderr,
                "Failed to find BPF program.\n");

        bpf_object__close(obj);
        return 1;
    }

    /*
     * STEP 4:
     * Attach the eBPF program to its hook.
     *
     * The SEC() declaration in the BPF program tells
     * libbpf which hook this program belongs to.
     */
    struct bpf_link *link;

    link = bpf_program__attach(prog);

    if (!link)
    {
        fprintf(stderr,
                "Failed to attach BPF program.\n");

        bpf_object__close(obj);
        return 1;
    }

    printf("BPF program attached successfully.\n");

    /*
     * STEP 5:
     * Keep the process alive.
     *
     * The BPF link remains active while this process
     * owns the link.
     */
    printf("eBPF program is running. Press Ctrl+C to stop.\n");

    while (1)
    {
        pause();
    }

    /*
     * Normally unreachable because of the infinite loop.
     * When we later handle signals properly, cleanup
     * will be added here.
     */
    bpf_link__destroy(link);
    bpf_object__close(obj);

    return 0;
}